[package]
name = "rust_discrete_event_simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary-heap-plus = "0.5.0"
rand = "0.8.5"
clap = { version = "4.1.4", features = ["derive"] }
